Models/Master/BidangResponse.cs
using PjlpCore.Entity;

namespace PjlpCore.Models.Master;

public class BidangResponse {
    public Object Bidang { get; set; }

    public int Total { get; set; }

    public BidangResponse(List<Bidang> bidang, int totalAl) {
        Bidang = bidang.Select(x => new {
            bidangID = x.BidangID,
            namaBidang = x.NamaBidang,
            kepalaBidang = x.KepalaBidang
        });

        Total = totalAl;
    }
}

Models/Master/DivisiViewModels.cs
using PjlpCore.Entity;

namespace PjlpCore.Models.Master;

public class DivisiViewModel {
    #nullable disable
    public Divisi Divisi { get; set; }

    #nullable enable
    public string? NamaBidang { get; set; }

    public bool IsNew { get; set; } = true;
}

Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Mvc;

namespace PjlpCore.Controllers;

public class AuthorizationController : Controller {

    [HttpGet("~/login")]
    public IActionResult LogIn(string returnUrl) {
        if (!string.IsNullOrEmpty(returnUrl)) {
            return Challenge(new AuthenticationProperties { RedirectUri = returnUrl }, OpenIdConnectDefaults.AuthenticationScheme);
        }

        return Challenge(new AuthenticationProperties { RedirectUri = "/dashboard"}, OpenIdConnectDefaults.AuthenticationScheme);
    }

    [HttpGet("~/logout"), HttpPost("~/logout")]
    public IActionResult LogOut() {
        return SignOut(CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme);
    }
}

Controllers/Master/AgamaController.cs
using Microsoft.AspNetCore.Mvc;
using PjlpCore.Entity;
using PjlpCore.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace PjlpCore.Controllers;

[Authorize(Roles = "SysAdmin, Kepeg")]
public class AgamaController : Controller {
    private IAgamaRepo repo;

    public AgamaController(IAgamaRepo agamaRepo) {
        repo = agamaRepo;
    }

    [Route("/master/agama")]
    public IActionResult Index() {
        return View("~/Views/Master/Agama/Index.cshtml");
    }

    [HttpGet("/master/agama/create")]
    public IActionResult Create() {
        return PartialView("~/Views/Master/Agama/AddEdit.cshtml", new Agama());
    }

    [HttpGet("/master/agama/edit")]
    public async Task<IActionResult> Edit(int agamaId) {
        return PartialView("~/Views/Master/Agama/AddEdit.cshtml", await repo.Agamas.FirstOrDefaultAsync(a => a.AgamaID == agamaId));
    }

    [HttpPost("/master/agama/save")]
    public async Task<IActionResult> SaveAgamaAsync(Agama agama) {
        if (ModelState.IsValid) {
            await repo.SaveAgamaAsync(agama);
            var result = new Dictionary<string, bool>();
            result.Add("success", true);
            return Json(result);
        }

        return PartialView("~/Views/Master/Agama/AddEdit.cshtml", agama);
    }
}

Controllers/Master/BidangController.cs
using Microsoft.AspNetCore.Mvc;
using PjlpCore.Entity;
using PjlpCore.Repository;
using PjlpCore.Hubs;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.Authorization;
using PjlpCore.Helpers;

namespace PjlpCore.Controllers;

[Authorize(Roles = "SysAdmin, Kepeg")]
public class BidangController : Controller {
    private IBidangRepo repo;    

    public BidangController(IBidangRepo bRepo) {
        repo = bRepo;        
    } 

    [HttpGet("/master/bidang")]
    public IActionResult Index() {
        return View("/Views/Master/Bidang/Index.cshtml");
    }


    [HttpGet("/master/bidang/create")]
    public IActionResult Create() => PartialView("/Views/Master/Bidang/AddEdit.cshtml", new Bidang { BidangID = Guid.Empty});

    [HttpGet("/master/bidang/edit")]
    public async Task<IActionResult> Edit(Guid bidangId) => PartialView("/Views/Master/Bidang/AddEdit.cshtml", 
        await repo.Bidangs.FirstOrDefaultAsync(b => b.BidangID == bidangId));

    [HttpPost("/master/bidang/save")]
    public async Task<IActionResult> SaveBidangAsync(Bidang bidang) {
        if (ModelState.IsValid) {
            await repo.SaveBidangAsync(bidang);
            return Json(Result.Success());
        } else {
            return PartialView("~/Views/Master/Bidang/AddEdit.cshtml", bidang);
        }
    }
}

Controllers/Master/DivisiController.cs
using Microsoft.AspNetCore.Mvc;
using PjlpCore.Models.Master;
using PjlpCore.Repository;
using PjlpCore.Entity;
using PjlpCore.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace PjlpCore.Controllers;

[Authorize(Roles = "SysAdmin, Kepeg")]
public class DivisiController : Controller {
    private IDivisiRepo repo;
    private IBidangRepo jabRepo;

    public DivisiController(IDivisiRepo kRepo, IBidangRepo pRepo) {
        repo = kRepo; jabRepo = pRepo;
    }

    [HttpGet("/master/divisi")]
    public IActionResult Index() {
        return View("~/Views/Master/Divisi/Index.cshtml");
    }

    [HttpGet("/master/divisi/create")]    
    public IActionResult Create() => PartialView("~/Views/Master/Divisi/AddEdit.cshtml", 
        new DivisiViewModel { Divisi = new Divisi(), IsNew = true });

    #nullable disable
    [HttpGet("/master/divisi/edit")]    
    public async Task<IActionResult> Edit(Guid divisiID) {
        Divisi div = await repo.Divisis.FirstOrDefaultAsync(k => k.DivisiID == divisiID);
        Bidang jab = await jabRepo.Bidangs.FirstOrDefaultAsync(p => p.BidangID == div.BidangID);

        return PartialView("~/Views/Master/Divisi/AddEdit.cshtml", new DivisiViewModel {
            Divisi = div,
            NamaBidang = jab.NamaBidang,
            IsNew = false
        });
    }

    [HttpPost("/master/divisi/save")]    
    public async Task<IActionResult> SaveDivisiAsync(DivisiViewModel div) {        
        if (ModelState.IsValid) {
            await repo.SaveDivisiAsync(div);
            return Json(Result.Success());
        } else {
            return PartialView("~/Views/Master/Divisi/AddEdit.cshtml", div);
        }
    }
}

Controllers/Master/JabatanController.cs
using Microsoft.AspNetCore.Mvc;
using PjlpCore.Models.Master;
using PjlpCore.Repository;
using PjlpCore.Entity;
using PjlpCore.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace PjlpCore.Controllers;

[Authorize(Roles = "SysAdmin, Kepeg, PjlpAdmin")]
public class JabatanController : Controller {
    private readonly IJabatanRepo repo;    

    public JabatanController(IJabatanRepo jRepo) {
        repo = jRepo;
    }

    [HttpGet("/master/jabatan")]
    public IActionResult Index() {
        return View("~/Views/Master/Jabatan/Index.cshtml");
    }

    [HttpGet("/master/jabatan/create")]    
    public IActionResult Create() => PartialView("~/Views/Master/Jabatan/AddEdit.cshtml", 
        new JabatanViewModel());

    #nullable disable
    [HttpGet("/master/jabatan/edit")]    
    public async Task<IActionResult> Edit(Guid jabatanID) {
        Jabatan div = await repo.Jabatans
            .Include(b => b.Bidang)
            .FirstOrDefaultAsync(k => k.JabatanID == jabatanID);        

        return PartialView("~/Views/Master/Jabatan/AddEdit.cshtml", new JabatanViewModel {
            Jabatan = div,
            NamaBidang = div.Bidang.NamaBidang
        });
    }

    [HttpPost("/master/jabatan/save")]    
    public async Task<IActionResult> SaveJabatanAsync(JabatanViewModel div) {
        // div.Jabatan.JabatanID = Guid.NewGuid();
        if (ModelState.IsValid) {
            await repo.SaveJabatanAsync(div);
            return Json(Result.Success());
        } else {
            return PartialView("~/Views/Master/Jabatan/AddEdit.cshtml", div);
        }
    }
}

Controllers/PendaftaranController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using PjlpCore.Entity;
using System.Security.Claims;
using PjlpCore.Models;
using PjlpCore.Repository;
using Microsoft.EntityFrameworkCore;
using PjlpCore.Helpers;
using System.Globalization;
using System.Text;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace PjlpCore.Controllers;

[Authorize]
public class PendaftaranController : Controller
{
    private readonly IPegawai repo;
    private readonly IPelamar pelamarRepo;
    private readonly IPegawai pegRepo;
    private readonly IFilePelamar fileRepo;
    private readonly IEventFile eventFileRepo;
    private readonly IEvent eventRepo;

    public PendaftaranController(IPegawai repo, IPelamar pRepo, IFilePelamar fRepo, IPegawai pegRepo, IEventFile eventFile, IEvent eventRepo)
    {
        this.repo = repo; 
        this.pelamarRepo = pRepo;
        this.fileRepo = fRepo;
        this.eventFileRepo = eventFile;
        this.pegRepo = pegRepo;
        this.eventRepo = eventRepo;
    }

    [HttpGet("/pendaftaran/index")]
    [Authorize(Roles = "PjlpUser")]
    public async Task<IActionResult> Index()
    {
        //DateTime closed = new(2022, 12, 12);

        //if (DateTime.Now > closed)
        //{
        //    return View("~/Views/Pendaftaran/TimeUp.cshtml");
        //}

        string? uid = ((ClaimsIdentity)User.Identity!).Claims.Where(c => c.Type == "sub").Select(c => c.Value).SingleOrDefault();
        string? email = ((ClaimsIdentity)User.Identity).Claims.Where(c => c.Type == "email").Select(c => c.Value).SingleOrDefault();
        string? ktp = User.Identity.Name;
        string? nama = ((ClaimsIdentity)User.Identity).Claims.Where(c => c.Type == "given_name").Select(c => c.Value).SingleOrDefault();

        Pegawai? peg = await repo.Pegawais
            .Where(x => x.NIK == ktp || x.Email == email)
            .Include(a => a.Agama)
            .Include(b => b.Bidang)
            .Include(p => p.Pendidikan)
            .Include(k => k.Kelurahan!.Kecamatan.Kabupaten.Provinsi)
            .Include(d => d.KelurahanDom!.Kecamatan.Kabupaten.Provinsi)
            .Include(x => x.DetailPjlp)
            .FirstOrDefaultAsync();

        string? lahir = "";
        bool isk2 = false;
        string? namabid = null;

        if (peg != null)
        {
            lahir = peg.TglLahir!.ToString();
            namabid = peg.Bidang.NamaBidang;

            if (peg!.DetailPjlp is null)
            {
                peg.DetailPjlp = new DetailPjlp();
            }

        } else
        {
            peg = new Pegawai { DetailPjlp = new DetailPjlp() };
        }

        TextInfo info = new CultureInfo("id_ID", false).TextInfo;

        return View(new PelamarVM
        {
            Pelamar = new Pelamar
            {
                UserId = Guid.Parse(uid!),
                UserEmail = email,
                NoKTP = ktp,
                Nama = nama!.ToUpper(),
                EventId = 1,
                Kelamin = peg!.Kelamin is null ? null : peg!.Kelamin!,
                GolonganDarah = peg!.GolDarah is null ? null : peg!.GolDarah!,
                // Tanggungan = peg!.DetailPjlp!.Tanggungan is null ? null : peg!.DetailPjlp!.Tanggungan,                
                IsK2 = isk2
            },
            Pegawai = peg,
            TanggalLahir = lahir != "" ? DateTime.Parse(lahir!).ToString("dd-MM-yyyy") : null,
            NamaAgama = peg!.AgamaID is null ? null : peg.Agama.NamaAgama,
            NamaPendidikan = peg!.PendidikanID is null ? null : peg.Pendidikan!.NamaPendidikan,
            Kelurahan = peg!.KelurahanID is null ? null : peg.Kelurahan!.NamaKelurahan,
            KecID = peg!.KelurahanID is null ? null : peg.Kelurahan!.KecamatanID,
            Kecamatan = peg!.KelurahanID is null ? null : peg.Kelurahan!.Kecamatan.NamaKecamatan,
            KabID = peg!.KelurahanID is null ? null : peg.Kelurahan!.Kecamatan.KabupatenID,
            Kabupaten = peg!.KelurahanID is null ? null : peg.Kelurahan!.Kecamatan.Kabupaten.NamaKabupaten,
            ProvID = peg!.KelurahanID is null ? null : peg.Kelurahan!.Kecamatan.Kabupaten.ProvinsiID,
            Provinsi = peg!.KelurahanID is null ? null : peg.Kelurahan!.Kecamatan.Kabupaten.Provinsi.NamaProvinsi,
            NamaBidang = namabid is null ? null : namabid

        });
    }

    [HttpGet("/pendaftaran/himbauan")]
    public IActionResult Himbauan()
    {
        return PartialView("~/Views/Pendaftaran/Himbauan.cshtml");
    }

    [HttpPost("/pendaftaran/store")]
    [Authorize(Roles = "PjlpUser")]
    public async Task<IActionResult> SavePendaftaran(PelamarVM model)
    {
        //DateTime closed = new(2022, 12, 12);

        //if (DateTime.Now > closed)
        //{
        //    return View("~/Views/Pendaftaran/TimeUp.cshtml");
        //}

        TextInfo info = new CultureInfo("id_ID", false).TextInfo;

        if (model.AddressIsSame)
        {
            model.Pelamar.NoKTP = User.Identity!.Name;
            model.Pelamar.DomKelurahanId = model.Pelamar.KelurahanId;
            model.Pelamar.DomAlamat = model.Pelamar.Alamat;
            model.Pelamar.DomRT = model.Pelamar.RT;
            model.Pelamar.DomRW = model.Pelamar.RW;
            model.Pelamar.DomKodePos = model.Pelamar.KodePos;
            model.Pelamar.AddressIsSame = model.AddressIsSame;
        }

        
        model.Pelamar.Nama = model.Pelamar.Nama.ToUpper();

        var pegawai = await pegRepo.Pegawais.Where(x => x.NIK == User.Identity!.Name).FirstOrDefaultAsync();

        if (pegawai is null)
        {
            model.Pelamar.IsNew = true;
        }

        model.Pelamar.StatusLamaranId = 1;
        model.Pelamar.TglLahir = DateOnly.Parse(model.TanggalLahir!, new CultureInfo("id-ID"));

        int isDewasa = GetAge(((DateOnly)model.Pelamar.TglLahir));

        if (isDewasa < 18)
        {
            model.Pelamar.StatusLamaranId = 6;
        }

        await pelamarRepo.SaveDataAsync(model.Pelamar);
        return Json(Result.Success());

        //return Json(Result.Failed());
    }

    [HttpGet("/pendaftaran/overview")]
    [Authorize(Roles = "PjlpUser")]
    public async Task<IActionResult> Overview()
    {
        Pelamar? data = await pelamarRepo.Pelamars
            .Where(x => x.NoKTP == User.Identity!.Name)
            .Include(a => a.Agama)
            .Include(b => b.Bidang)
            .Include(p => p.Pendidikan)
            .Include(j => j.Jabatan)
            .Include(e => e.Event)
            .Include(x => x.StatusLamaran)
            .Include(k => k.Kelurahan!.Kecamatan.Kabupaten.Provinsi)
            .Include(d => d.KelurahanDom!.Kecamatan.Kabupaten.Provinsi)
            .FirstOrDefaultAsync();

        if (data is null)
        {
            return RedirectToAction("Index");
        }        

        if (data is not null)
        {
            string? lahir = data.TglLahir.ToString();
            string? sim = "";

            int HarusUpload = await eventFileRepo.EventFiles
            .Where(x => x.JabatanID == data.JabatanId)
            .Where(x => x.IsNew == data.IsNew)
            .CountAsync();

            List<FilePelamar>? filePelamar = await fileRepo.FilePelamars
                .Where(x => x.PelamarId == data!.PelamarId)
                .Include(p => p.Persyaratan)
                .OrderByDescending(p => p.CreatedAt)
                .ToListAsync();

            int SudahUpload = filePelamar is null ? 0 : filePelamar.Count();
            int BelumUpload = HarusUpload - SudahUpload;

            string pasfoto = "";

            BelumUpload = BelumUpload < 0 ? 0 : BelumUpload;

            sim = data.TglAkhirSIM is not null ? data.TglAkhirSIM!.ToString() : "";

            if (filePelamar is not null)
            {
                if (filePelamar.Any(x => x.PersyaratanID == 2))
                {
#nullable disable
                    pasfoto = filePelamar.Where(x => x.PersyaratanID == 2).Select(x => x.FilePath + "/" + x.FileName).FirstOrDefault();
#nullable enable
                }
            }            

            return View("~/Views/Pendaftaran/Overview.cshtml", new PelamarVM
            {
                Pelamar = data,
                NamaAgama = data.Agama.NamaAgama,
                NamaBidang = data.Bidang.NamaBidang,
                NamaPendidikan = data.Pendidikan!.NamaPendidikan,
                TanggalLahir = DateTime.Parse(lahir!).ToString("dd-MM-yyyy"),
                Kelurahan = data.KelurahanId is null ? "" : data.Kelurahan!.NamaKelurahan,
                Kecamatan = data.KelurahanId is null ? "" : data.Kelurahan!.Kecamatan.NamaKecamatan,
                KecID = data.KelurahanId is null ? "" : data.Kelurahan!.KecamatanID,
                KabID = data.KelurahanId is null ? "" : data.Kelurahan!.Kecamatan.KabupatenID,
                Kabupaten = data.KelurahanId is null ? "" : data.Kelurahan!.Kecamatan.Kabupaten.NamaKabupaten,
                ProvID = data.KelurahanId is null ? "" : data.Kelurahan!.Kecamatan.Kabupaten.ProvinsiID,
                Provinsi = data.KelurahanId is null ? "" : data.Kelurahan!.Kecamatan.Kabupaten.Provinsi.NamaProvinsi,
                KelurahanDom = data.DomKelurahanId is null ? "" : data.KelurahanDom!.NamaKelurahan,
                KecDomID = data.DomKelurahanId is null ? "" : data.KelurahanDom!.KecamatanID,
                KecamatanDom = data.DomKelurahanId is null ? "" : data.KelurahanDom!.Kecamatan.NamaKecamatan,
                KabDomID = data.DomKelurahanId is null ? "" : data.KelurahanDom!.Kecamatan.KabupatenID,
                KabupatenDom = data.DomKelurahanId is null ? "" : data.KelurahanDom!.Kecamatan.Kabupaten.NamaKabupaten,
                ProvDomID = data.DomKelurahanId is null ? "" : data.KelurahanDom!.Kecamatan.Kabupaten.ProvinsiID,
                ProvinsiDom = data.DomKelurahanId is null ? "" : data.KelurahanDom!.Kecamatan.Kabupaten.Provinsi.NamaProvinsi,
                AddressIsSame = (bool)data.AddressIsSame!,

Views/Shared/_DropdownApp.cshtml
<div class="dropdown-header bg-trans-gradient d-flex justify-content-center align-items-center rounded-top">
    <h4 class="m-0 text-center color-white">
        Quick Shortcut
        <small class="mb-0 opacity-80">User Applications & Addons</small>
    </h4>
</div>
<div class="custom-scroll h-100">
    <ul class="app-list">
        <li>
            <a href="#" class="app-list-item hover-white">

                <span class="icon-stack">
                    <i class="base-2 icon-stack-3x color-primary-600"></i>
                    <i class="base-3 icon-stack-2x color-primary-700"></i>
                    <i class="ni ni-settings icon-stack-1x text-white fs-lg"></i>
                </span>

                <span class="app-list-name">
                    Services
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">

                <span class="icon-stack">
                    <i class="base-2 icon-stack-3x color-primary-400"></i>
                    <i class="base-10 text-white icon-stack-1x"></i>
                    <i class="ni md-profile color-primary-800 icon-stack-2x"></i>
                </span>

                <span class="app-list-name">
                    Account
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">

                <span class="icon-stack">
                    <i class="base-9 icon-stack-3x color-success-400"></i>
                    <i class="base-2 icon-stack-2x color-success-500"></i>
                    <i class="ni ni-shield icon-stack-1x text-white"></i>
                </span>

                <span class="app-list-name">
                    Security
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">

                <span class="icon-stack">
                    <i class="base-18 icon-stack-3x color-info-700"></i>
                    <span class="position-absolute pos-top pos-left pos-right color-white fs-md mt-2 fw-400">28</span>
                </span>

                <span class="app-list-name">
                    Calendar
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">

                <span class="icon-stack">
                    <i class="base-7 icon-stack-3x color-info-500"></i>
                    <i class="base-7 icon-stack-2x color-info-700"></i>
                    <i class="ni ni-graph icon-stack-1x text-white"></i>
                </span>
                <span class="app-list-name">
                    Stats
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">
                <span class="icon-stack">
                    <i class="base-4 icon-stack-3x color-danger-500"></i>
                    <i class="base-4 icon-stack-1x color-danger-400"></i>
                    <i class="ni ni-envelope icon-stack-1x text-white"></i>
                </span>
                <span class="app-list-name">
                    Messages
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">
                <span class="icon-stack">
                    <i class="base-4 icon-stack-3x color-fusion-400"></i>
                    <i class="base-5 icon-stack-2x color-fusion-200"></i>
                    <i class="base-5 icon-stack-1x color-fusion-100"></i>
                    <i class="fal fa-keyboard icon-stack-1x color-info-50"></i>
                </span>
                <span class="app-list-name">
                    Notes
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">
                <span class="icon-stack">
                    <i class="base-16 icon-stack-3x color-fusion-500"></i>
                    <i class="base-10 icon-stack-1x color-primary-50 opacity-30"></i>
                    <i class="base-10 icon-stack-1x fs-xl color-primary-50 opacity-20"></i>
                    <i class="fal fa-dot-circle icon-stack-1x text-white opacity-85"></i>
                </span>
                <span class="app-list-name">
                    Photos
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">
                <span class="icon-stack">
                    <i class="base-19 icon-stack-3x color-primary-400"></i>
                    <i class="base-7 icon-stack-2x color-primary-300"></i>
                    <i class="base-7 icon-stack-1x fs-xxl color-primary-200"></i>
                    <i class="base-7 icon-stack-1x color-primary-500"></i>
                    <i class="fal fa-globe icon-stack-1x text-white opacity-85"></i>
                </span>
                <span class="app-list-name">
                    Maps
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">
                <span class="icon-stack">
                    <i class="base-5 icon-stack-3x color-success-700 opacity-80"></i>
                    <i class="base-12 icon-stack-2x color-success-700 opacity-30"></i>
                    <i class="fal fa-comment-alt icon-stack-1x text-white"></i>
                </span>
                <span class="app-list-name">
                    Chat
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">
                <span class="icon-stack">
                    <i class="base-5 icon-stack-3x color-warning-600"></i>
                    <i class="base-7 icon-stack-2x color-warning-800 opacity-50"></i>
                    <i class="fal fa-phone icon-stack-1x text-white"></i>
                </span>
                <span class="app-list-name">
                    Phone
                </span>
            </a>
        </li>
        <li>
            <a href="#" class="app-list-item hover-white">
                <span class="icon-stack">
                    <i class="base-6 icon-stack-3x color-danger-600"></i>
                    <i class="fal fa-chart-line icon-stack-1x text-white"></i>
                </span>
                <span class="app-list-name">
                    Projects
                </span>
            </a>
        </li>
        <li class="w-100">
            <a href="#" class="btn btn-default mt-4 mb-2 pr-5 pl-5"> Add more apps </a>
        </li>
    </ul>
</div>

Views/Shared/_DropdownMenu.cshtml
@using System.Security.Claims

<div class="dropdown-header bg-trans-gradient d-flex flex-row py-4 rounded-top">
    <div class="d-flex flex-row align-items-center mt-1 mb-1 color-white">
        <span class="mr-2">
            <img src="~/images//logo/logo-dinas-75.png" class="rounded-circle profile-image" alt="User">
        </span>
        <div class="info-card-text">
            <div class="fs-lg text-truncate text-truncate-lg">
                @{
                    #nullable disable
                    if (User.Identity.IsAuthenticated) {
                        @(((ClaimsIdentity)User.Identity!).Claims.Where(c => c.Type == "given_name").Select(c => c.Value).SingleOrDefault())
                    }
                }
            </div>
            <span class="text-truncate text-truncate-md opacity-80">
                @if (User.IsInRole("PjlpAdmin") || User.IsInRole("SysAdmin")) {
                    <span>Admin System</span>
                } else if (User.IsInRole("PjlpUser")) {
                    <span>User PJLP</span>
                }            
            </span>
        </div>
    </div>
</div>
<div class="dropdown-divider m-0"></div>
<a href="#" class="dropdown-item" data-action="app-reset">
    <span data-i18n="drpdwn.reset_layout">Reset Layout</span>
</a>
<a href="#" class="dropdown-item" data-toggle="modal" data-target=".js-modal-settings">
    <span data-i18n="drpdwn.settings">Settings</span>
</a>
<div class="dropdown-divider m-0"></div>

<a href="#" class="dropdown-item" data-action="app-fullscreen">
    <span data-i18n="drpdwn.fullscreen">Fullscreen</span>
    <i class="float-right text-muted fw-n">F11</i>
</a>
<a href="#" class="dropdown-item" data-action="app-print">
    <span data-i18n="drpdwn.print">Print</span>
    <i class="float-right text-muted fw-n">Ctrl + P</i>
</a>
<div class="dropdown-divider m-0"></div>
<a class="dropdown-item fw-500 pt-3 pb-3" asp-controller="Authorization" asp-action="LogOut">
    <span data-i18n="drpdwn.page-logout">Logout</span>
    <span class="float-right fw-n"></span>
</a>

Views/Shared/_NavPJLP.cshtml
<ul id="js-nav-menu" class="nav-menu">
    <li class='@(ViewBag.Title == "Overview" ? "active" : "")'>
        <a asp-action="Overview" asp-controller="Pendaftaran" title="Tinjauaan" data-filter-tags="Tinjauan">
            <i class="fal fa-home"></i>
            <span class="nav-link-text" data-i18n="nav.tinjauan">Tinjauan</span>
        </a>
        
    </li>
    <li class='@(ViewBag.Title == "Berkas" ? "active" : "")'>
        <a asp-action="Berkas" asp-controller="Pendaftaran" title="Dashboard" data-filter-tags="Berkas">
            <i class="fal fa-files"></i>
            <span class="nav-link-text" data-i18n="nav.berkas">Berkas</span>
        </a>    </li>
    
</ul>